### ISSUE TITLE
Youtube upload

### ISSUE THREAD

**Issue by 12345ieee** [csaboka/spacechempatch#19]
The YT upload uses an old API that doesn't work anymore.

Either disallow the user from trying an upload (gray out or remove the button) or get it to work again.

**Comment by csaboka** [comment]
Looks like fixing YT upload would be a real pain. The current API only supports OAuth2 authentication, which in turn requires someone to create authorization credentials in their Google account. Those credentials then need to be kept secret to make sure no one can impersonate your client (SpaceChem in our case) and make changes on its behalf.

Keeping secrets in an open source project isn't really possible. The closest we could get is a closed-source webservice running somewhere online, which takes requests from SpaceChem and sends them to YouTube with the right authentication. It's just not worth it for a hobby project.

Removing the button, on the other hand, should be easy now that we mostly understand how the GUI works.

**Comment by csaboka** [comment]
I've just pushed a patch that allows removing YT upload functionality altogether. Videos are automatically saved to the desktop instead, since that's the only remaining option.

Note that the solution recording button still says that you can upload the video to YT. Changing this text would mean we're introducing new text to the game. We would either have to translate that new text to each supported language, or have it show up in English for everyone. I'd rather not open that can of worms now.
