### ISSUE TITLE
OS-independent RNG

### ISSUE THREAD

**Issue by RandomPanda0** [csaboka/spacechempatch#21]
SpaceChem's RNG is OS-dependent.  It'd be nice to make it OS-independent, by allowing all OSs to use the same RNG algorithms, however that might be done.

**Comment by csaboka** [comment]
I'm making good progress on this. I'm planning it to be a pair of mutually exclusive patches, one that uses the Windows RNG regardless of your OS and another that uses the Linux RNG. Of course, the former will be useless on Windows and the latter on Linux, but since the patcher itself is OS-independent, I'd rather not complicate it by hiding the useless patch based on your OS.

**Comment by csaboka** [comment]
This is implemented in the master branch now, and will be part of the next release.

I could verify that by enforcing the Linux RNG on my Windows machine, Introduction to Sensing gave me the Linux sequence documented at https://www.reddit.com/r/spacechem/wiki/gamemechanics#wiki_os_randomness , while enforcing Windows RNG gave me the same thing I would get with a vanilla game.
