### ISSUE TITLE
Multiple Non-Bonder Glyphs

### ISSUE THREAD

**Issue by RandomPanda0** [csaboka/spacechempatch#22]
Alright, here's a novel gameplay idea that might not be impossible to implement:

Multiple glyphs for sensing, fusing, or splitting.  The game always gives us one, but it would be interesting to have the capacity.  Should work the same way bonders do, just activate them all at once.

Swapping is also an idea, but that one can't be so "easily" implemented.  Maybe a cycling over the available glyphs?  It'd require the code for these guys to be known.

**Comment by csaboka** [comment]
We already know where instructions and reactor features are implemented, so it actually wouldn't be that difficult to tweak their behavior. (Sensors, fusers and splitters probably wouldn't even need tweaking, they already activate all corresponding features. Swapper would need changes, since it's written not to do anything if the number of tunnels is anything other than 2.) Adding a proper UI to the ResearchNet puzzle editor so it allows you to select more than one of such features would be a bit harder, but we have a good idea about that as well.

What I'm worried about is splitting the player base by having puzzles that are only playable with a modded game. The ResearchNet puzzle descriptions only have a boolean field for sensors, fusers, splitters and swappers, so an unmodded game would not be able to load puzzles like this properly. It would be a big step towards making "modded Spacechem" a different game from plain old regular Spacechem.

If the community is OK with having things like this in the patcher, it would be an interesting challenge to implement, but I have my concerns about what the long-term effects would be.

**Comment by RandomPanda0** [comment]
Is it possible to abuse some other part of the ResNet description to add information about the number of glyphs in the game?  I'm not too sure how the puzzle description might work.  If we only had to mod the puzzle making aspect of the game, that'd be way cool.

Otherwise, I'd argue that adding gameplay elements like this couldn't possibly split the userbase, since there's no part of the userbase playing "new" levels (the last new level posted on /r/researchnet was 11 months ago).  I think adding this stuff could lead to the first resurgence in new SpaceChem content in a long time.

Excluding the tourney, of course.  If the tournament host wanted to use the modded client for that, then I think it would simply take some instructing of the userbase - which shouldn't be too hard to do.

Anyways, that's just my input as a piece of the community, it definitely warrants a discussion.

**Comment by csaboka** [comment]
I have just pushed code to the master branch to implement this. Seems to work as expected based on some quick testing, but will need some beta testing before I consider it stable.

Puzzles that use this feature won't load properly in the unmodified game. There shouldn't be any crashes or similar nastiness, but the vanilla game will trim out all the extra glyphs from your solution, so you need to be careful. See the README for details.
