### ISSUE TITLE
Relationship with "SpaceChem community update (v1013)"?

### ISSUE THREAD

**Issue by SamB** [csaboka/spacechempatch#34]
It looks like a lot of your (@csaboka and @12345ieee's) work got incorporated into [SpaceChem community update (v1013)](https://steamcommunity.com/games/92800/announcements/detail/1737729728308220584).  (I mean, they credited you and everything!)

So I'm wondering if there's anything they left out, and if this makes it harder to use spacechempatch (to get whatever they left out, or to make additional changes).

[I'm also wondering how the update changes the exact rules, but that's presumably more a problem for [r/spacechem](https://www.reddit.com/r/spacechem/), since they own https://www.reddit.com/r/spacechem/wiki/gamemechanics and all.]

**Comment by csaboka** [comment]
I can't tell you anything concrete right now, but we're hoping to customize SpaceChem with a different approach that doesn't involve patching the official executable. Zach was kind enough to give us access to the source control of the game and let us implement things into the main game for v1013. He's willing to let us create and maintain a branch there for an edition of the game that has niche features and less stable code.

If we can make this work, it would mean we wouldn't distribute a patch to the game, but an alternative executable with extra features. It would also mean that our changes will be owned by Zachtronics and will obviously be closed source, so if we keep using GitHub, it will only be for issue tracking and distribution of the binary, but not for source control.

**Comment by 12345ieee** [comment]
I want to precise that the plan @csaboka talked about is still tentative and we're still discussing it internally.

When we'll get to a satisfactory point, we'll let the community know.

As of now, SpaceChemPatch is unusable on v1013 (by design) because of the hash protection, I do not recommend trying to modify the patcher to go through without waiting for us, that would probably break your game.

The proper game didn't get all the features the mod has, as some of them are too hacky, disrupt the UI or allow you to make illegal bonds.

------------------------------

I'll answer for r/spacechem as well (even if the correct place to ask would be there) as I'm a mod of it as well.
I am obviously aware of how the game rules changed with this update, we will update the mechanics wiki and the leaderboard, it's just going to take time.

**Comment by csaboka** [comment]
It has taken longer than originally anticipated, but with the release of [Community Edition](https://github.com/spacechem-community-developers/SpaceChem-Community-Edition) today, you have your definite answer :)
